//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightDataEntities : DbContext
    {
        public FlightDataEntities()
            : base("name=FlightDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<View_RawNoRegime_Bad> View_RawNoRegime_Bad { get; set; }
        public virtual DbSet<View_RawNoRegime_Good> View_RawNoRegime_Good { get; set; }
        public virtual DbSet<RawNoRegime> RawNoRegimes { get; set; }
    }
}
